
// Actions Tyepes
export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";


export const ADD_NEWS_REQUEST = "ADD_NEWS_REQUEST";

//All Routes
export const FETCH_ALL_ROUTES_REQUEST = "FETCH_ALL_ROUTES_REQUEST";
export const FETCH_ALL_ROUTES_SUCCESS = "FETCH_ALL_ROUTES_SUCCESS";
export const FETCH_ALL_ROUTES_FAILURE = "FETCH_ALL_ROUTES_FAILURE";

//Single Route
export const FETCH_ROUTE_REQUEST = "FETCH_ROUTE_REQUEST";
export const FETCH_ROUTE_SUCCESS = "FETCH_ROUTE_SUCCESS";
export const FETCH_ROUTE_FAILURE = "FETCH_ROUTE_FAILURE";
